@baseUrl = {{$dotenv BASE_URL}}

###
# @name createCustomer
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/customers HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name createManyCustomer
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/customers/create-many HTTP/1.1
Accept: application/json
Content-Type: application/json

[
  {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
]

###
# @name retrieveAllCustomer
GET {{baseUrl}}/v1/customers HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name retrieveCustomer
# @prompt id
GET {{baseUrl}}/v1/customers/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name updateCustomer
# @prompt id
# @prompt name
# @prompt phone
PATCH {{baseUrl}}/v1/customers/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name updateManyCustomer
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/customers/update-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "filter": {
    "name": "{{name}}"
  },
  "data": {
    "phone": "{{phone}}"
  }
}

###
# @name deleteCustomer
# @prompt id
DELETE {{baseUrl}}/v1/customers/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name deleteManyCustomer
# @prompt id1
# @prompt id2
POST {{baseUrl}}/v1/customers/delete-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "ids": ["{{id1}}","{{id2}}"]
}

###
# @name createTransactionCustomer
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/customers/transaction HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "data1": {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  "data2": {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
}